import { Hospital, Doctor, Appointment, Prescription, Review, EmergencyCategory } from '../types';

export const EMERGENCY_CATEGORIES: EmergencyCategory[] = [
  {
    id: 'cardiology',
    name: 'Cardiology',
    iconName: 'HeartPulse',
    description: 'Chest pain, cardiac arrest, arrhythmia, severe pressure',
    color: 'from-red-500 to-rose-600',
  },
  {
    id: 'neurology',
    name: 'Neurology',
    iconName: 'Brain',
    description: 'Stroke symptoms, paralysis, severe head trauma, seizures',
    color: 'from-purple-500 to-indigo-600',
  },
  {
    id: 'trauma',
    name: 'Trauma & Critical',
    iconName: 'Activity',
    description: 'Accidents, deep wound lacerations, heavy bleeding',
    color: 'from-amber-500 to-red-600',
  },
  {
    id: 'orthopedic',
    name: 'Orthopedic',
    iconName: 'Bone',
    description: 'Fractures, joint dislocation, spine impact trauma',
    color: 'from-blue-500 to-cyan-600',
  },
  {
    id: 'burns',
    name: 'Burns Unit',
    iconName: 'Flame',
    description: 'Chemical, electrical, or thermal skin burns & scalds',
    color: 'from-orange-500 to-amber-600',
  },
  {
    id: 'ambulance',
    name: 'Ambulance 24/7',
    iconName: 'Ambulance',
    description: 'Immediate mobile ICU ambulance dispatch with paramedic',
    color: 'from-red-600 to-red-700',
  },
  {
    id: 'general',
    name: 'General Emergency',
    iconName: 'Stethoscope',
    description: 'High fever, acute abdominal pain, poisoning, severe allergy',
    color: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'pediatric',
    name: 'Pediatric Emergency',
    iconName: 'Baby',
    description: 'Infant respiratory distress, pediatric convulsions, high fever',
    color: 'from-sky-500 to-blue-600',
  },
];

export const INITIAL_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-1',
    name: 'Apollo Multi-Speciality Super Hospital',
    tagline: 'World-Class Healthcare & Emergency Care Excellence',
    registrationNumber: 'MED-APO-99482',
    ownerName: 'Dr. Pratap C. Reddy',
    address: 'Sarita Vihar, Mathura Road, New Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110076',
    email: 'contact@apollodehli.medconnect.ai',
    phone: '+91-11-2692-5858',
    emergencyNumber: '1066',
    latitude: 28.5355,
    longitude: 77.2882,
    images: [
      'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1000&q=80'
    ],
    description: 'Apollo Hospitals is Asia’s premier integrated healthcare services provider with 50+ specialities, 24/7 level-1 trauma center, robotic surgery units, and advanced cardiac catheterization labs.',
    departments: ['Cardiology', 'Neurology', 'Orthopedics', 'Pediatrics', 'Oncology', 'Emergency & Trauma', 'Dermatology'],
    treatments: ['Coronary Angioplasty', 'Spine Surgery', 'Bone Marrow Transplant', 'Robotic Knee Replacement', 'Stroke Rehabilitation'],
    totalBeds: 450,
    availableBeds: 62,
    totalICUBeds: 85,
    availableICUBeds: 14,
    hasAmbulance: true,
    workingHours: '24/7 Emergency & OPD (8:00 AM - 8:00 PM)',
    rating: 4.9,
    reviewCount: 1240,
  },
  {
    id: 'hosp-2',
    name: 'Max Super Speciality Hospital',
    tagline: 'Precision Medicine & Advanced Surgical Care',
    registrationNumber: 'MED-MAX-77319',
    ownerName: 'Max Healthcare Institute',
    address: 'Press Enclave Road, Saket, New Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110017',
    email: 'info@maxhealthcare.medconnect.ai',
    phone: '+91-11-2651-5050',
    emergencyNumber: '011-4055-4055',
    latitude: 28.5280,
    longitude: 77.2115,
    images: [
      'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=1000&q=80'
    ],
    description: 'Max Super Speciality Hospital Saket features 500+ beds, 15 state-of-the-art operation theatres, comprehensive burn care center, and neuro-interventional trauma care.',
    departments: ['Cardiology', 'Neurology', 'Gastroenterology', 'Burns & Plastic Surgery', 'Pediatrics', 'Nephrology'],
    treatments: ['Liver Transplant', 'Brain Tumor Excision', 'Dialysis', 'Coronary Bypass', 'Pediatric ICU Care'],
    totalBeds: 500,
    availableBeds: 88,
    totalICUBeds: 90,
    availableICUBeds: 18,
    hasAmbulance: true,
    workingHours: '24/7 Open',
    rating: 4.8,
    reviewCount: 980,
  },
  {
    id: 'hosp-3',
    name: 'Fortis Escorts Heart & Multispeciality Institute',
    tagline: 'Leading Heart Care & Critical Emergency Unit',
    registrationNumber: 'MED-FOR-33102',
    ownerName: 'Fortis Healthcare Ltd',
    address: 'Okhla Road, Sukhdev Vihar, New Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110025',
    email: 'emergency@fortisescorts.medconnect.ai',
    phone: '+91-11-4713-5000',
    emergencyNumber: '105010',
    latitude: 28.5601,
    longitude: 77.2735,
    images: [
      'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=1000&q=80'
    ],
    description: 'Pioneers in cardiac care, heart transplants, pediatric cardiology, and emergency trauma triage.',
    departments: ['Cardiology', 'Pulmonology', 'Orthopedics', 'General Surgery', 'Trauma'],
    treatments: ['Heart Valve Repair', 'Pacemaker Implantation', 'Angiography', 'Asthma Care'],
    totalBeds: 310,
    availableBeds: 40,
    totalICUBeds: 60,
    availableICUBeds: 9,
    hasAmbulance: true,
    workingHours: '24/7 Emergency',
    rating: 4.7,
    reviewCount: 750,
  },
  {
    id: 'hosp-4',
    name: 'Manipal Hospital Dwarka',
    tagline: 'Compassionate Patient-Centric Medical Care',
    registrationNumber: 'MED-MNP-55201',
    ownerName: 'Manipal Health Enterprises',
    address: 'Sector 6, Dwarka, New Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110075',
    email: 'dwarka@manipalhospitals.medconnect.ai',
    phone: '+91-11-4040-7070',
    emergencyNumber: '011-4040-9999',
    latitude: 28.5921,
    longitude: 77.0460,
    images: [
      'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=1000&q=80'
    ],
    description: 'Modern tertiary care hospital equipped with digital ICU beds, emergency trauma teams, and advanced radiological scanning.',
    departments: ['Neurology', 'Orthopedics', 'Pediatrics', 'Dermatology', 'ENT'],
    treatments: ['Sinus Surgery', 'Skin Laser Therapy', 'Arthroscopy', 'Child Vaccination'],
    totalBeds: 380,
    availableBeds: 95,
    totalICUBeds: 50,
    availableICUBeds: 21,
    hasAmbulance: true,
    workingHours: '24/7 Emergency & OPD (9:00 AM - 7:00 PM)',
    rating: 4.8,
    reviewCount: 620,
  }
];

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    userId: 'user-doc-1',
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Multi-Speciality Super Hospital',
    name: 'Dr. Rajesh Sharma',
    photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=500&q=80',
    qualification: 'MBBS, MD (General Medicine), DM (Cardiology)',
    specialization: 'Cardiology',
    experienceYears: 18,
    medicalRegistrationNumber: 'DMC-CARD-88192',
    email: 'rajesh.sharma@apollo.medconnect.ai',
    phone: '+91-98112-34567',
    consultationFee: 1200,
    languages: ['English', 'Hindi'],
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['09:00 AM', '10:30 AM', '11:45 AM', '02:30 PM', '04:00 PM'],
    rating: 4.9,
    reviewCount: 340,
    bio: 'Senior Interventional Cardiologist specializing in complex angioplasty, transcatheter aortic valve replacement (TAVR), and acute heart failure triage.',
  },
  {
    id: 'doc-2',
    userId: 'user-doc-2',
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Multi-Speciality Super Hospital',
    name: 'Dr. Ananya Iyer',
    photo: 'https://images.unsplash.com/photo-1594824813566-88855ce78347?auto=format&fit=crop&w=500&q=80',
    qualification: 'MBBS, MS (Neuro Surgery), MCh',
    specialization: 'Neurology',
    experienceYears: 14,
    medicalRegistrationNumber: 'DMC-NEURO-55421',
    email: 'ananya.iyer@apollo.medconnect.ai',
    phone: '+91-98765-43210',
    consultationFee: 1500,
    languages: ['English', 'Hindi', 'Tamil'],
    availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
    availableSlots: ['10:00 AM', '11:30 AM', '03:00 PM', '05:15 PM'],
    rating: 4.95,
    reviewCount: 280,
    bio: 'Lead Neurosurgeon specializing in stroke interventions, brain tumor microsurgery, and endoscopic spine surgery.',
  },
  {
    id: 'doc-3',
    userId: 'user-doc-3',
    hospitalId: 'hosp-2',
    hospitalName: 'Max Super Speciality Hospital',
    name: 'Dr. Vikramaditya Gupta',
    photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=500&q=80',
    qualification: 'MBBS, MS (Orthopedics), Fellowship in Joint Replacement (UK)',
    specialization: 'Orthopedics',
    experienceYears: 16,
    medicalRegistrationNumber: 'DMC-ORTHO-11094',
    email: 'vikram.gupta@max.medconnect.ai',
    phone: '+91-98109-87654',
    consultationFee: 1100,
    languages: ['English', 'Hindi', 'Punjabi'],
    availableDays: ['Tuesday', 'Thursday', 'Friday', 'Saturday'],
    availableSlots: ['09:30 AM', '11:00 AM', '02:00 PM', '04:30 PM'],
    rating: 4.85,
    reviewCount: 410,
    bio: 'Pioneer in robotic total knee and hip replacement surgery with over 4,000 successful procedures.',
  },
  {
    id: 'doc-4',
    userId: 'user-doc-4',
    hospitalId: 'hosp-2',
    hospitalName: 'Max Super Speciality Hospital',
    name: 'Dr. Meera Kapoor',
    photo: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=500&q=80',
    qualification: 'MBBS, MD (Pediatrics), DCH',
    specialization: 'Pediatrics',
    experienceYears: 12,
    medicalRegistrationNumber: 'DMC-PEDS-77382',
    email: 'meera.kapoor@max.medconnect.ai',
    phone: '+91-98991-12233',
    consultationFee: 900,
    languages: ['English', 'Hindi'],
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    availableSlots: ['08:30 AM', '10:00 AM', '11:30 AM', '05:00 PM'],
    rating: 4.9,
    reviewCount: 520,
    bio: 'Dedicated Pediatrician focusing on child immunization, growth monitoring, and pediatric infectious disease emergency care.',
  },
  {
    id: 'doc-5',
    userId: 'user-doc-5',
    hospitalId: 'hosp-3',
    hospitalName: 'Fortis Escorts Heart & Multispeciality Institute',
    name: 'Dr. Siddharth Verma',
    photo: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=500&q=80',
    qualification: 'MBBS, MD (Dermatology, Venereology & Leprosy)',
    specialization: 'Dermatology',
    experienceYears: 10,
    medicalRegistrationNumber: 'DMC-DERM-33291',
    email: 'siddharth.verma@fortis.medconnect.ai',
    phone: '+91-99554-43322',
    consultationFee: 850,
    languages: ['English', 'Hindi'],
    availableDays: ['Monday', 'Wednesday', 'Friday'],
    availableSlots: ['11:00 AM', '01:00 PM', '04:00 PM', '06:00 PM'],
    rating: 4.75,
    reviewCount: 195,
    bio: 'Consultant Dermatologist specializing in clinical dermatology, skin infections, allergic dermatitis, and laser procedures.',
  }
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-101',
    patientId: 'patient-demo',
    patientName: 'Rahul Verma',
    patientPhone: '+91-98765-11223',
    patientEmail: 'rahul.verma@example.com',
    patientAge: 32,
    patientGender: 'Male',
    doctorId: 'doc-1',
    doctorName: 'Dr. Rajesh Sharma',
    doctorSpecialization: 'Cardiology',
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Multi-Speciality Super Hospital',
    department: 'Cardiology',
    date: '2026-09-24',
    timeSlot: '10:30 AM',
    status: 'confirmed',
    symptoms: 'Occasional tightness in chest after climbing stairs.',
    bookingDate: '2026-09-20',
    fee: 1200,
    paymentStatus: 'Paid',
  },
  {
    id: 'apt-102',
    patientId: 'patient-demo',
    patientName: 'Rahul Verma',
    patientPhone: '+91-98765-11223',
    patientEmail: 'rahul.verma@example.com',
    patientAge: 32,
    patientGender: 'Male',
    doctorId: 'doc-4',
    doctorName: 'Dr. Meera Kapoor',
    doctorSpecialization: 'Pediatrics',
    hospitalId: 'hosp-2',
    hospitalName: 'Max Super Speciality Hospital',
    department: 'Pediatrics',
    date: '2026-08-15',
    timeSlot: '11:30 AM',
    status: 'completed',
    symptoms: 'Child fever consultation and MMR vaccination guidance.',
    bookingDate: '2026-08-12',
    fee: 900,
    paymentStatus: 'Insurance Covered',
    prescriptionId: 'pres-501',
  }
];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'pres-501',
    appointmentId: 'apt-102',
    patientId: 'patient-demo',
    patientName: 'Rahul Verma (Son: Aarav)',
    patientAge: 5,
    patientGender: 'Male',
    doctorId: 'doc-4',
    doctorName: 'Dr. Meera Kapoor',
    doctorRegistration: 'DMC-PEDS-77382',
    doctorSpecialization: 'Pediatrics',
    hospitalId: 'hosp-2',
    hospitalName: 'Max Super Speciality Hospital',
    date: '2026-08-15',
    vitals: {
      bloodPressure: 'N/A',
      pulseRate: '110 bpm',
      temperature: '100.2 °F',
      weightKg: '18 kg',
    },
    diagnosis: 'Acute Viral Fever with mild URI',
    medicines: [
      {
        name: 'Syrup Paracetamol (250mg/5ml)',
        dosage: '5 ml',
        frequency: 'Every 6 hours if fever > 100°F',
        durationDays: 3,
        instructions: 'Give after food with water',
      },
      {
        name: 'Syrup Cetirizine (5mg/5ml)',
        dosage: '2.5 ml',
        frequency: '0-0-1 (At Bedtime)',
        durationDays: 5,
        instructions: 'Helps relieve nasal congestion',
      }
    ],
    advice: 'Keep child well hydrated with ORS and warm water. Avoid cold beverages. Tepid sponging if temp exceeds 101°F.',
    followUpDate: '2026-08-20',
    digitalSignatureUrl: 'Dr. Meera Kapoor [Verified]',
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    patientId: 'pat-1',
    patientName: 'Sanjay Kumar',
    targetId: 'hosp-1',
    targetType: 'hospital',
    rating: 5,
    comment: 'Exceptional emergency care response when my father suffered acute chest pain. The team had him in the cath lab within 15 minutes!',
    date: '2026-09-10',
  },
  {
    id: 'rev-2',
    patientId: 'pat-2',
    patientName: 'Priya Nair',
    targetId: 'doc-1',
    targetType: 'doctor',
    rating: 5,
    comment: 'Dr. Rajesh Sharma is extremely patient and explained the angioplasty procedure clearly. Highly recommended!',
    date: '2026-09-02',
  },
  {
    id: 'rev-3',
    patientId: 'pat-3',
    patientName: 'Amitabh Sen',
    targetId: 'hosp-2',
    targetType: 'hospital',
    rating: 4.8,
    comment: 'Clean facilities, seamless appointment check-in, and great nursing staff.',
    date: '2026-08-28',
  }
];
